sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
services: mongodb
script:
- meteor test-packages --velocity --driver-package velocity:console-reporter
